### PR TITLE
Build examples as an option

### PR DESCRIPTION
**Pull request by drewr95**
This makes building the examples optional

### CODE REVIEW

**Comment by erikerlandson** [comment]
thanks @drewr95 !

could you tweak the documentation to mention the test/example options?
https://github.com/erikerlandson/st_tree#install

**Comment by drewr95** [comment]
@erikerlandson np, hopefully the documentation updated to what you wanted :]

**Comment by erikerlandson** [comment]
@drewr95  yes that's what I had in mind!   Can you please rebase on develop?  My CI workflow isn't running on your PR and I think it is because I had it slightly misconfigured

**Comment by drewr95** [comment]
@erikerlandson How's this? I've never done this before, so excuse any mistakes I possibly made.

**Comment by erikerlandson** [comment]
strange, it's still not running the ci.  Well, I'll merge this and figure out my workflow problems elsewhere

**Pull request merged**
