### PR TITLE
Fix Unreachable Code Warning For is_ancestor

### PR DESCRIPTION
**Pull request by drewr95**
#32 I referenced my fork and the Tasking Tricore compiler no longer reports the warning

### CODE REVIEW

**Comment by erikerlandson** [comment]
several of these commits seem to be duplicates of the previous pull request

**Comment by drewr95** [comment]
Yeah I tried rebasing again and I think that's what happened :/.  Do you want me to remove this and try again?

**Comment by erikerlandson** [comment]
yeah, I guess make sure you have the latest `develop` and recreate it from there?

**Comment by drewr95** [comment]
Yeah I can do that. I'll close this one.  Sorry about that!

**Pull request closed without merging**
